@startuml
class Admin {
    - id: int
    - username: string
    - password: string
  }

  class ManageUser {
    + suspendUser(string userID, bool confirmSuspend): bool
  }


  class Report {
    - id: int
    - title: string
    - description: string
    + generateReport(int startDate, int endDate, bool userType): bool
    + deleteReport(): void
    + archiveReport(): void
    + downloadReport(): void
  }


Admin --> ManageUser
ManageUser --> Admin
Report --> Admin
@enduml